Repository ManageIQ/manageiq-consumption, pull requests merged in 2018-10, with the labels that each got.

#141 [HAMMER] Update i18n catalog for hammer
  locale/ManageIQ_Showback.pot
  locale/en/ManageIQ_Showback.po
  locale/es/ManageIQ_Showback.po
  locale/fr/ManageIQ_Showback.po
  locale/ja/ManageIQ_Showback.po
  locale/pt_BR/ManageIQ_Showback.po
  locale/zanata.xml
  locale/zh_CN/ManageIQ_Showback.po
Labels: internationalization

#142 [HAMMER] [Changelog] Update for Hammer Beta1 release
  CHANGELOG.md
Labels: documentation

#143 Bump Travis to PG 9.5
  .travis.yml
Labels: technical debt

#144 Remove deprecation warning `use_i18n` is deprecated
  config/initializers/money.rb
Labels: technical debt, test
