Repository ManageIQ/manageiq-consumption, pull requests merged in 2020-10, with the labels that each got.

#173 [initializers/money.rb] Set rounding_mode
  config/initializers/money.rb
Labels: cleanup

#178 Plugin Generator Updates
  .codeclimate.yml
  .gitignore
  .rspec
  .rspec_ci
  .rubocop.yml
  .rubocop_cc.yml
  .travis.yml
  .yamllint
  Gemfile
  LICENSE.txt
  README.md
  Rakefile
  bin/ci/after_script
  bin/update
  bundler.d/.keep
  config/settings.yml
  lib/manageiq-consumption.rb
  lib/manageiq/showback/engine.rb
  lib/tasks/README.md
  lib/tasks_private/spec.rake
  locale/.keep
  manageiq-consumption.gemspec
  spec/spec_helper.rb
Labels: developer

#179 Test with ruby 2.5.8 and 2.6.6
  .travis.yml
Labels: dependencies

#180 Use manageiq-style
  .codeclimate.yml
  .rubocop.yml
  .rubocop_cc.yml
  manageiq-consumption.gemspec
Labels: developer, enhancement
